package org.bhawanisingh.calotes.api.license;

public class Boost1 extends GenericLicense {

	public Boost1() {
		LICENSE_NAME = "BOOST1";
		// Do's
		COMMERCIAL_USE = DO;
		DISTRIBUTE = DO;
		MODIFY = DO;

		// Don'ts
		HOLD_LIABLE = DO_NOT;

		// MUST
		INCLUDE_COPYRIGHT_NOTICE = MUST;
		INCLUDE_LICENSE = MUST;

		// NotApplicable
		DISCLOSE_SOURCE = NOT_APPLICABLE;
		INCLUDE_ORIGINAL = NOT_APPLICABLE;
		NON_STATIC_LINKAGE = NOT_APPLICABLE;
		PRIVATE_USE = NOT_APPLICABLE;
		RENAME = NOT_APPLICABLE;
		STATE_CHANGES = NOT_APPLICABLE;
		SUBLICENSE = NOT_APPLICABLE;
		USE_TRADEMARK = NOT_APPLICABLE;
		WARRANTY = NOT_APPLICABLE;
	}
}